WITH INST_GDE_4TH_TMP AS(
SELECT ACCTG_DT
       ,INST_ID
       ,INST_NME
       ,INST_GDE
       ,INDEX_NO
       ,INDEX_VALUE
FROM (
--------------------------------------------------------------------------------------------
--第一段
SELECT DATE'2024-10-31'                                                  AS ACCTG_DT
       ,COALESCE(T2.INST_ID,T2_1.DOMN_INST_ID)                           AS INST_ID
       ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)                         AS INST_NME
       ,'4'                                                              AS INST_GDE
       ,CASE WHEN T1.ACCTG_SBJEC_ID LIKE '121%' THEN '12AA'
             WHEN T1.ACCTG_SBJEC_ID LIKE '123%' THEN '22AA' END          AS INDEX_NO
       ,SUM(CASE WHEN T1.CCY<>'CNY' THEN T1.BAL*T3.RATE ELSE T1.BAL END) AS INDEX_VALUE  
              
FROM B_GEMS_LOAN_INFO T1--贷款基础表

LEFT JOIN B_PBLC_INST_INFO T2--机构信息表
ON T1.ACTOPE_INST_ID=T2.INST_ID--贷款在网点办理
AND T2.ACCTG_DT='20241031'

LEFT JOIN (SELECT PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME
           FROM B_PBLC_INST_INFO--机构信息表
           WHERE ACCTG_DT='20241031'
           GROUP BY PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME) T2_1
ON T1.ACTOPE_INST_ID=T2_1.DOMN_INST_ID--贷款在辖行办理           

LEFT JOIN CCY_RATE T3--币种汇率表
ON T1.CCY=T3.CCY_OLD
AND T3.CCY_NEW='CNY'
AND BGN_DT<=DATE'2024-10-31'
AND END_DT> DATE'2024-10-31'
 
WHERE T1.ACCTG_DT='20241031'--月底最后一天 
AND T1.BAL<>'0'--余额未结清
AND (T1.ACCTG_SBJEC_ID LIKE '121%' OR T1.ACCTG_SBJEC_ID LIKE '123%')--科目号121和123开头

GROUP BY COALESCE(T2.INST_ID,T2_1.DOMN_INST_ID)
         ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME) 
         ,CASE WHEN T1.ACCTG_SBJEC_ID LIKE '121%' THEN '12AA'
               WHEN T1.ACCTG_SBJEC_ID LIKE '123%' THEN '22AA' END--不会存在null
UNION ALL
--------------------------------------------------------------------------------------------
--第二段
SELECT DATE'2024-10-31'                                                  AS ACCTG_DT
       ,COALESCE(T2.INST_ID,T2_1.DOMN_INST_ID)                           AS INST_ID
       ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)                         AS INST_NME
       ,'4'                                                              AS INST_GDE
       ,CASE WHEN T4.ENTP_SCAL_CD IN ('01','02') THEN '12AB'  
             WHEN T4.ENTP_SCAL_CD='03' THEN '12AC'
             WHEN T4.ENTP_SCAL_CD='04' THEN '12AD' END                   AS INDEX_NO
       ,SUM(CASE WHEN T1.CCY<>'CNY' THEN T1.BAL*T3.RATE ELSE T1.BAL END) AS INDEX_VALUE
                
FROM B_GEMS_LOAN_INFO T1

LEFT JOIN B_PBLC_INST_INFO T2--机构信息表
ON T1.ACTOPE_INST_ID=T2.INST_ID--贷款在网点办理
AND T2.ACCTG_DT='20241031'

LEFT JOIN (SELECT PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME
           FROM B_PBLC_INST_INFO--机构信息表
           WHERE ACCTG_DT='20241031'
           GROUP BY PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME) T2_1
ON T1.ACTOPE_INST_ID=T2_1.DOMN_INST_ID--贷款在辖行办理           

LEFT JOIN CCY_RATE T3
ON T1.CCY=T3.CCY_OLD
AND T3.CCY_NEW='CNY'
AND BGN_DT<=DATE'2024-10-31'
AND END_DT> DATE'2024-10-31'

LEFT JOIN B_ECIF_CUST_INFO_C T4--客户表
ON T1.CUST_ID=T4.CUST_ID
AND T4.ACCTG_DT='20241031'

WHERE T1.ACCTG_DT='20241031'--月底最后一天 
AND T1.BAL<>'0'--余额未结清
AND (T1.ACCTG_SBJEC_ID LIKE '121%' OR T1.ACCTG_SBJEC_ID LIKE '123%')--科目号121和123开头

GROUP BY COALESCE(T2.INST_ID,T2_1.DOMN_INST_ID)
         ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME) 
         ,CASE WHEN T4.ENTP_SCAL_CD IN ('01','02') THEN '12AB'  
               WHEN T4.ENTP_SCAL_CD='03' THEN '12AC'
               WHEN T4.ENTP_SCAL_CD='04' THEN '12AD' END--可能存在null
UNION ALL
--------------------------------------------------------------------------------------------
--第三段
SELECT DATE'2024-10-31'                                                  AS ACCTG_DT
       ,COALESCE(T2.INST_ID,T2_1.DOMN_INST_ID)                           AS INST_ID
       ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)                         AS INST_NME
       ,'4'                                                              AS INST_GDE
       ,CASE WHEN T4.ENTP_SCAL_CD IN ('01','02') AND T5.CREDIT_LMT<5000000.00 THEN '12AB1'--  
               WHEN T4.ENTP_SCAL_CD IN ('01','02') AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12AB2'--
               WHEN T4.ENTP_SCAL_CD IN ('01','02') AND T5.CREDIT_LMT>=10000000.00 THEN '12AB3'-- 
               WHEN T4.ENTP_SCAL_CD='03' AND T5.CREDIT_LMT<5000000.00 THEN '12AC1'--
               WHEN T4.ENTP_SCAL_CD='03' AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12AC2'--
               WHEN T4.ENTP_SCAL_CD='03' AND T5.CREDIT_LMT>=10000000.00 THEN '12AC3'--
               WHEN T4.ENTP_SCAL_CD='04' AND T5.CREDIT_LMT<5000000.00 THEN '12AD1'--
               WHEN T4.ENTP_SCAL_CD='04' AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12AD2'--
               WHEN T4.ENTP_SCAL_CD='04' AND T5.CREDIT_LMT>=10000000.00 THEN '12AD3'--      
               END                                                       AS INDEX_NO
       ,SUM(CASE WHEN T1.CCY<>'CNY' THEN T1.BAL*T3.RATE ELSE T1.BAL END) AS INDEX_VALUE
                
FROM B_GEMS_LOAN_INFO T1

LEFT JOIN B_PBLC_INST_INFO T2--机构信息表
ON T1.ACTOPE_INST_ID=T2.INST_ID--贷款在网点办理
AND T2.ACCTG_DT='20241031'

LEFT JOIN (SELECT PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME
           FROM B_PBLC_INST_INFO--机构信息表
           WHERE ACCTG_DT='20241031'
           GROUP BY PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME) T2_1
ON T1.ACTOPE_INST_ID=T2_1.DOMN_INST_ID--贷款在辖行办理           

LEFT JOIN CCY_RATE T3
ON T1.CCY=T3.CCY_OLD
AND T3.CCY_NEW='CNY'
AND BGN_DT<=DATE'2024-10-31'
AND END_DT> DATE'2024-10-31'

LEFT JOIN B_ECIF_CUST_INFO_C T4--客户表
ON T1.CUST_ID=T4.CUST_ID
AND T4.ACCTG_DT='20241031'

LEFT JOIN B_ECIF_CUST_LMT T5--客户授信额度表
ON T1.CUST_ID=T5.CUST_ID
AND T5.ACCTG_DT='20241031'

WHERE T1.ACCTG_DT='20241031'--月底最后一天 
AND T1.BAL<>'0'--余额未结清
AND (T1.ACCTG_SBJEC_ID LIKE '121%' OR T1.ACCTG_SBJEC_ID LIKE '123%')--科目号121和123开头

GROUP BY COALESCE(T2.INST_ID,T2_1.DOMN_INST_ID)--
         ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)-- 
         ,CASE WHEN T4.ENTP_SCAL_CD IN ('01','02') AND T5.CREDIT_LMT<5000000.00 THEN '12AB1'--  
               WHEN T4.ENTP_SCAL_CD IN ('01','02') AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12AB2'--
               WHEN T4.ENTP_SCAL_CD IN ('01','02') AND T5.CREDIT_LMT>=10000000.00 THEN '12AB3'-- 
               WHEN T4.ENTP_SCAL_CD='03' AND T5.CREDIT_LMT<5000000.00 THEN '12AC1'--
               WHEN T4.ENTP_SCAL_CD='03' AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12AC2'--
               WHEN T4.ENTP_SCAL_CD='03' AND T5.CREDIT_LMT>=10000000.00 THEN '12AC3'--
               WHEN T4.ENTP_SCAL_CD='04' AND T5.CREDIT_LMT<5000000.00 THEN '12AD1'--
               WHEN T4.ENTP_SCAL_CD='04' AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12AD2'--
               WHEN T4.ENTP_SCAL_CD='04' AND T5.CREDIT_LMT>=10000000.00 THEN '12AD3'--      
               END--可能存在null
UNION ALL
--------------------------------------------------------------------------------------------
--第四段
SELECT DATE'2024-10-31'                                                  AS ACCTG_DT
       ,COALESCE(T2.INST_ID,T2_1.DOMN_INST_ID)                           AS INST_ID
       ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)                         AS INST_NME
       ,'4'                                                              AS INST_GDE
       ,CASE WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='1' THEN '12BA'-- 
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='2' THEN '12BB'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='3' THEN '12BC'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='4' THEN '12BD'--      
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='5' THEN '12BE'--
               END                                                       AS INDEX_NO
       ,SUM(CASE WHEN T1.CCY<>'CNY' THEN T1.BAL*T3.RATE ELSE T1.BAL END) AS INDEX_VALUE
                
FROM B_GEMS_LOAN_INFO T1

LEFT JOIN B_PBLC_INST_INFO T2--机构信息表
ON T1.ACTOPE_INST_ID=T2.INST_ID--贷款在网点办理
AND T2.ACCTG_DT='20241031'

LEFT JOIN (SELECT PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME
           FROM B_PBLC_INST_INFO--机构信息表
           WHERE ACCTG_DT='20241031'
           GROUP BY PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME) T2_1
ON T1.ACTOPE_INST_ID=T2_1.DOMN_INST_ID--贷款在辖行办理           

LEFT JOIN CCY_RATE T3
ON T1.CCY=T3.CCY_OLD
AND T3.CCY_NEW='CNY'
AND BGN_DT<=DATE'2024-10-31'
AND END_DT> DATE'2024-10-31'

LEFT JOIN B_RISK_LOAN_FIVE_CLASS T6--贷款五级分类表
ON T1.UNVS_AGM_NO=T6.UNVS_AGM_NO
AND T1.AGM_MODIF=T6.AGM_MODIF
AND T6.ACCTG_DT='20241031'

WHERE T1.ACCTG_DT='20241031'--月底最后一天 
AND T1.BAL<>'0'--余额未结清
AND (T1.ACCTG_SBJEC_ID LIKE '121%' OR T1.ACCTG_SBJEC_ID LIKE '123%')--科目号121和123开头

GROUP BY COALESCE(T2.INST_ID,T2_1.DOMN_INST_ID)--
         ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)-- 
         ,CASE WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='1' THEN '12BA'-- 
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='2' THEN '12BB'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='3' THEN '12BC'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='4' THEN '12BD'--      
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='5' THEN '12BE'--
               END--不会存在null  
UNION ALL
--------------------------------------------------------------------------------------------
--第五段
SELECT DATE'2024-10-31'                                                  AS ACCTG_DT
       ,COALESCE(T2.INST_ID,T2_1.DOMN_INST_ID)                           AS INST_ID
       ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)                         AS INST_NME
       ,'4'                                                              AS INST_GDE
       ,CASE WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS) IN ('3','4','5') THEN '12BF' 
             END                                                         AS INDEX_NO
       ,SUM(CASE WHEN T1.CCY<>'CNY' THEN T1.BAL*T3.RATE ELSE T1.BAL END) AS INDEX_VALUE
                
FROM B_GEMS_LOAN_INFO T1

LEFT JOIN B_PBLC_INST_INFO T2--机构信息表
ON T1.ACTOPE_INST_ID=T2.INST_ID--贷款在网点办理
AND T2.ACCTG_DT='20241031'

LEFT JOIN (SELECT PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME
           FROM B_PBLC_INST_INFO--机构信息表
           WHERE ACCTG_DT='20241031'
           GROUP BY PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME) T2_1
ON T1.ACTOPE_INST_ID=T2_1.DOMN_INST_ID--贷款在辖行办理           

LEFT JOIN CCY_RATE T3
ON T1.CCY=T3.CCY_OLD
AND T3.CCY_NEW='CNY'
AND BGN_DT<=DATE'2024-10-31'
AND END_DT> DATE'2024-10-31'

LEFT JOIN B_RISK_LOAN_FIVE_CLASS T6--贷款五级分类表
ON T1.UNVS_AGM_NO=T6.UNVS_AGM_NO
AND T1.AGM_MODIF=T6.AGM_MODIF
AND T6.ACCTG_DT='20241031'

WHERE T1.ACCTG_DT='20241031'--月底最后一天 
AND T1.BAL<>'0'--余额未结清
AND (T1.ACCTG_SBJEC_ID LIKE '121%' OR T1.ACCTG_SBJEC_ID LIKE '123%')--科目号121和123开头

GROUP BY COALESCE(T2.INST_ID,T2_1.DOMN_INST_ID)--
         ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)-- 
         ,CASE WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS) IN ('3','4','5') THEN '12BF' END--可能存在null
UNION ALL
--------------------------------------------------------------------------------------------
--第六段
SELECT DATE'2024-10-31'                                                  AS ACCTG_DT
       ,COALESCE(T2.INST_ID,T2_1.DOMN_INST_ID)                           AS INST_ID
       ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)                         AS INST_NME
       ,'4'                                                              AS INST_GDE
       ,CASE WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='1' AND T5.CREDIT_LMT<5000000.00 THEN '12BA1'-- 
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='1' AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12BA2'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='1' AND T5.CREDIT_LMT>=10000000.00 THEN '12BA3'-- 
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='2' AND T5.CREDIT_LMT<5000000.00 THEN '12BB1'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='2' AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12BB2'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='2' AND T5.CREDIT_LMT>=10000000.00 THEN '12BB3'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='3' AND T5.CREDIT_LMT<5000000.00 THEN '12BC1'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='3' AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12BC2'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='3' AND T5.CREDIT_LMT>=10000000.00 THEN '12BC3'--     
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='4' AND T5.CREDIT_LMT<5000000.00 THEN '12BD1'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='4' AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12BD2'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='4' AND T5.CREDIT_LMT>=10000000.00 THEN '12BD3'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='5' AND T5.CREDIT_LMT<5000000.00 THEN '12BE1'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='5' AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12BE2'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='5' AND T5.CREDIT_LMT>=10000000.00 THEN '12BE3'--
               END                                                       AS INDEX_NO
       ,SUM(CASE WHEN T1.CCY<>'CNY' THEN T1.BAL*T3.RATE ELSE T1.BAL END) AS INDEX_VALUE
                
FROM B_GEMS_LOAN_INFO T1

LEFT JOIN B_PBLC_INST_INFO T2--机构信息表
ON T1.ACTOPE_INST_ID=T2.INST_ID--贷款在网点办理
AND T2.ACCTG_DT='20241031'

LEFT JOIN (SELECT PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME
           FROM B_PBLC_INST_INFO--机构信息表
           WHERE ACCTG_DT='20241031'
           GROUP BY PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME) T2_1
ON T1.ACTOPE_INST_ID=T2_1.DOMN_INST_ID--贷款在辖行办理           

LEFT JOIN CCY_RATE T3
ON T1.CCY=T3.CCY_OLD
AND T3.CCY_NEW='CNY'
AND BGN_DT<=DATE'2024-10-31'
AND END_DT> DATE'2024-10-31'

LEFT JOIN B_ECIF_CUST_LMT T5--客户授信额度表
ON T1.CUST_ID=T5.CUST_ID
AND T5.ACCTG_DT='20241031'

LEFT JOIN B_RISK_LOAN_FIVE_CLASS T6--贷款五级分类表
ON T1.UNVS_AGM_NO=T6.UNVS_AGM_NO
AND T1.AGM_MODIF=T6.AGM_MODIF
AND T6.ACCTG_DT='20241031'

WHERE T1.ACCTG_DT='20241031'--月底最后一天 
AND T1.BAL<>'0'--余额未结清
AND (T1.ACCTG_SBJEC_ID LIKE '121%' OR T1.ACCTG_SBJEC_ID LIKE '123%')--科目号121和123开头

GROUP BY COALESCE(T2.INST_ID,T2_1.DOMN_INST_ID)--
         ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)-- 
         ,CASE WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='1' AND T5.CREDIT_LMT<5000000.00 THEN '12BA1'-- 
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='1' AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12BA2'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='1' AND T5.CREDIT_LMT>=10000000.00 THEN '12BA3'-- 
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='2' AND T5.CREDIT_LMT<5000000.00 THEN '12BB1'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='2' AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12BB2'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='2' AND T5.CREDIT_LMT>=10000000.00 THEN '12BB3'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='3' AND T5.CREDIT_LMT<5000000.00 THEN '12BC1'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='3' AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12BC2'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='3' AND T5.CREDIT_LMT>=10000000.00 THEN '12BC3'--     
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='4' AND T5.CREDIT_LMT<5000000.00 THEN '12BD1'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='4' AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12BD2'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='4' AND T5.CREDIT_LMT>=10000000.00 THEN '12BD3'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='5' AND T5.CREDIT_LMT<5000000.00 THEN '12BE1'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='5' AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12BE2'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS)='5' AND T5.CREDIT_LMT>=10000000.00 THEN '12BE3'--
               END--不会存在null
UNION ALL
--------------------------------------------------------------------------------------------
--第七段
SELECT DATE'2024-10-31'                                                  AS ACCTG_DT
       ,COALESCE(T2.INST_ID,T2_1.DOMN_INST_ID)                           AS INST_ID
       ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)                         AS INST_NME
       ,'4'                                                              AS INST_GDE
       ,CASE WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS) IN ('3','4','5') AND T5.CREDIT_LMT<5000000.00 THEN '12BF1'-- 
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS) IN ('3','4','5') AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12BF2'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS) IN ('3','4','5') AND T5.CREDIT_LMT>=10000000.00 THEN '12BF3'--
               END                                                       AS INDEX_NO
       ,SUM(CASE WHEN T1.CCY<>'CNY' THEN T1.BAL*T3.RATE ELSE T1.BAL END) AS INDEX_VALUE
                
FROM B_GEMS_LOAN_INFO T1

LEFT JOIN B_PBLC_INST_INFO T2--机构信息表
ON T1.ACTOPE_INST_ID=T2.INST_ID--贷款在网点办理
AND T2.ACCTG_DT='20241031'

LEFT JOIN (SELECT PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME
           FROM B_PBLC_INST_INFO--机构信息表
           WHERE ACCTG_DT='20241031'
           GROUP BY PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME) T2_1
ON T1.ACTOPE_INST_ID=T2_1.DOMN_INST_ID--贷款在辖行办理           

LEFT JOIN CCY_RATE T3
ON T1.CCY=T3.CCY_OLD
AND T3.CCY_NEW='CNY'
AND BGN_DT<=DATE'2024-10-31'
AND END_DT> DATE'2024-10-31'

LEFT JOIN B_ECIF_CUST_LMT T5--客户授信额度表
ON T1.CUST_ID=T5.CUST_ID
AND T5.ACCTG_DT='20241031'

LEFT JOIN B_RISK_LOAN_FIVE_CLASS T6--贷款五级分类表
ON T1.UNVS_AGM_NO=T6.UNVS_AGM_NO
AND T1.AGM_MODIF=T6.AGM_MODIF
AND T6.ACCTG_DT='20241031'

WHERE T1.ACCTG_DT='20241031'--月底最后一天 
AND T1.BAL<>'0'--余额未结清
AND (T1.ACCTG_SBJEC_ID LIKE '121%' OR T1.ACCTG_SBJEC_ID LIKE '123%')--科目号121和123开头

GROUP BY COALESCE(T2.INST_ID,T2_1.DOMN_INST_ID)--
         ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)-- 
         ,CASE WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS) IN ('3','4','5') AND T5.CREDIT_LMT<5000000.00 THEN '12BF1'-- 
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS) IN ('3','4','5') AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12BF2'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS) IN ('3','4','5') AND T5.CREDIT_LMT>=10000000.00 THEN '12BF3'--
               END--可能存在null
UNION ALL
--------------------------------------------------------------------------------------------
--第八段
SELECT DATE'2024-10-31'                                                  AS ACCTG_DT
       ,COALESCE(T2.INST_ID,T2_1.DOMN_INST_ID)                           AS INST_ID
       ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)                         AS INST_NME
       ,'4'                                                              AS INST_GDE
       ,CASE WHEN T4.HOLD_SHARE='COL' THEN '12CA'--  
               WHEN T4.HOLD_SHARE='PER' THEN '12CB'--
               WHEN T4.HOLD_SHARE='HAT' THEN '12CC'-- 
               WHEN T4.HOLD_SHARE='FOR' THEN '12CD'--
               WHEN T4.HOLD_SHARE='CTY' THEN '12CE'--
               END                                                       AS INDEX_NO
       ,SUM(CASE WHEN T1.CCY<>'CNY' THEN T1.BAL*T3.RATE ELSE T1.BAL END) AS INDEX_VALUE
                
FROM B_GEMS_LOAN_INFO T1

LEFT JOIN B_PBLC_INST_INFO T2--机构信息表
ON T1.ACTOPE_INST_ID=T2.INST_ID--贷款在网点办理
AND T2.ACCTG_DT='20241031'

LEFT JOIN (SELECT PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME
           FROM B_PBLC_INST_INFO--机构信息表
           WHERE ACCTG_DT='20241031'
           GROUP BY PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME) T2_1
ON T1.ACTOPE_INST_ID=T2_1.DOMN_INST_ID--贷款在辖行办理           

LEFT JOIN CCY_RATE T3
ON T1.CCY=T3.CCY_OLD
AND T3.CCY_NEW='CNY'
AND BGN_DT<=DATE'2024-10-31'
AND END_DT> DATE'2024-10-31'

LEFT JOIN B_ECIF_CUST_INFO_C T4--客户表
ON T1.CUST_ID=T4.CUST_ID
AND T4.ACCTG_DT='20241031'

WHERE T1.ACCTG_DT='20241031'--月底最后一天 
AND T1.BAL<>'0'--余额未结清
AND (T1.ACCTG_SBJEC_ID LIKE '121%' OR T1.ACCTG_SBJEC_ID LIKE '123%')--科目号121和123开头

GROUP BY COALESCE(T2.INST_ID,T2_1.DOMN_INST_ID)--
         ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)-- 
         ,CASE WHEN T4.HOLD_SHARE='COL' THEN '12CA'--  
               WHEN T4.HOLD_SHARE='PER' THEN '12CB'--
               WHEN T4.HOLD_SHARE='HAT' THEN '12CC'-- 
               WHEN T4.HOLD_SHARE='FOR' THEN '12CD'--
               WHEN T4.HOLD_SHARE='CTY' THEN '12CE'--
               END
UNION ALL
--------------------------------------------------------------------------------------------
--第九段
SELECT DATE'2024-10-31'                                                  AS ACCTG_DT
       ,COALESCE(T2.INST_ID,T2_1.DOMN_INST_ID)                           AS INST_ID
       ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)                         AS INST_NME
       ,'4'                                                              AS INST_GDE
       ,CASE WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS) IN ('3','4','5') AND T4.HOLD_SHARE='COL' THEN '12CA1'--  
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS) IN ('3','4','5') AND T4.HOLD_SHARE='PER' THEN '12CB1'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS) IN ('3','4','5') AND T4.HOLD_SHARE='HAT' THEN '12CC1'-- 
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS) IN ('3','4','5') AND T4.HOLD_SHARE='FOR' THEN '12CD1'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS) IN ('3','4','5') AND T4.HOLD_SHARE='CTY' THEN '12CE1'--
               END                                                       AS INDEX_NO
       ,SUM(CASE WHEN T1.CCY<>'CNY' THEN T1.BAL*T3.RATE ELSE T1.BAL END) AS INDEX_VALUE
                
FROM B_GEMS_LOAN_INFO T1

LEFT JOIN B_PBLC_INST_INFO T2--机构信息表
ON T1.ACTOPE_INST_ID=T2.INST_ID--贷款在网点办理
AND T2.ACCTG_DT='20241031'

LEFT JOIN (SELECT PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME
           FROM B_PBLC_INST_INFO--机构信息表
           WHERE ACCTG_DT='20241031'
           GROUP BY PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME) T2_1
ON T1.ACTOPE_INST_ID=T2_1.DOMN_INST_ID--贷款在辖行办理           

LEFT JOIN CCY_RATE T3
ON T1.CCY=T3.CCY_OLD
AND T3.CCY_NEW='CNY'
AND BGN_DT<=DATE'2024-10-31'
AND END_DT> DATE'2024-10-31'

LEFT JOIN B_ECIF_CUST_INFO_C T4--客户表
ON T1.CUST_ID=T4.CUST_ID
AND T4.ACCTG_DT='20241031'

LEFT JOIN B_RISK_LOAN_FIVE_CLASS T6--贷款五级分类表
ON T1.UNVS_AGM_NO=T6.UNVS_AGM_NO
AND T1.AGM_MODIF=T6.AGM_MODIF
AND T6.ACCTG_DT='20241031'

WHERE T1.ACCTG_DT='20241031'--月底最后一天 
AND T1.BAL<>'0'--余额未结清
AND (T1.ACCTG_SBJEC_ID LIKE '121%' OR T1.ACCTG_SBJEC_ID LIKE '123%')--科目号121和123开头

GROUP BY COALESCE(T2.INST_ID,T2_1.DOMN_INST_ID)--
         ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)-- 
         ,CASE WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS) IN ('3','4','5') AND T4.HOLD_SHARE='COL' THEN '12CA1'--  
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS) IN ('3','4','5') AND T4.HOLD_SHARE='PER' THEN '12CB1'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS) IN ('3','4','5') AND T4.HOLD_SHARE='HAT' THEN '12CC1'-- 
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS) IN ('3','4','5') AND T4.HOLD_SHARE='FOR' THEN '12CD1'--
               WHEN COALESCE(T6.FINAL_FIVE_CLASS,T6.FIVE_CLASS) IN ('3','4','5') AND T4.HOLD_SHARE='CTY' THEN '12CE1'--
               END               
UNION ALL
--------------------------------------------------------------------------------------------
--第十段
SELECT DATE'2024-10-31'                                                  AS ACCTG_DT
       ,COALESCE(T2.INST_ID,T2_1.DOMN_INST_ID)                           AS INST_ID
       ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)                         AS INST_NME
       ,'4'                                                              AS INST_GDE
       ,CASE WHEN T7.CONTRACT_GUAR_TP='01' THEN '12DA'--  
               WHEN T7.CONTRACT_GUAR_TP='02' THEN '12DB'--
               WHEN T7.CONTRACT_GUAR_TP='03' THEN '12DC'--
               WHEN T7.CONTRACT_GUAR_TP='04' THEN '12DD'--
               WHEN T7.CONTRACT_GUAR_TP='05' THEN '12DE'--       
               END                                                       AS INDEX_NO
       ,SUM(CASE WHEN T1.CCY<>'CNY' THEN T1.BAL*T3.RATE ELSE T1.BAL END) AS INDEX_VALUE
                
FROM B_GEMS_LOAN_INFO T1

LEFT JOIN B_PBLC_INST_INFO T2--机构信息表
ON T1.ACTOPE_INST_ID=T2.INST_ID--贷款在网点办理
AND T2.ACCTG_DT='20241031'

LEFT JOIN (SELECT PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME
           FROM B_PBLC_INST_INFO--机构信息表
           WHERE ACCTG_DT='20241031'
           GROUP BY PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME) T2_1
ON T1.ACTOPE_INST_ID=T2_1.DOMN_INST_ID--贷款在辖行办理           

LEFT JOIN CCY_RATE T3--币种汇率表
ON T1.CCY=T3.CCY_OLD
AND T3.CCY_NEW='CNY'
AND BGN_DT<=DATE'2024-10-31'
AND END_DT> DATE'2024-10-31'

LEFT JOIN B_GEMS_LOAN_CONTRACT_INFO T7 --贷款合同表
ON T1.UNVS_AGM_NO=T7.UNVS_AGM_NO
AND T1.AGM_MODIF=T7.AGM_MODIF
AND T7.ACCTG_DT='20241031'

WHERE T1.ACCTG_DT='20241031'--月底最后一天 
AND T1.BAL<>'0'--余额未结清
AND (T1.ACCTG_SBJEC_ID LIKE '121%' OR T1.ACCTG_SBJEC_ID LIKE '123%')--科目号121和123开头

GROUP BY COALESCE(T2.INST_ID,T2_1.DOMN_INST_ID)--
         ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)-- 
         ,CASE WHEN T7.CONTRACT_GUAR_TP='01' THEN '12DA'--  
               WHEN T7.CONTRACT_GUAR_TP='02' THEN '12DB'--
               WHEN T7.CONTRACT_GUAR_TP='03' THEN '12DC'--
               WHEN T7.CONTRACT_GUAR_TP='04' THEN '12DD'--
               WHEN T7.CONTRACT_GUAR_TP='05' THEN '12DE'--       
               END--可能存在null
UNION ALL
--------------------------------------------------------------------------------------------
--第十一段
SELECT DATE'2024-10-31'                                                  AS ACCTG_DT
       ,COALESCE(T2.INST_ID,T2_1.DOMN_INST_ID)                           AS INST_ID
       ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)                         AS INST_NME
       ,'4'                                                              AS INST_GDE
        ,CASE WHEN T7.CONTRACT_GUAR_TP='01' AND T5.CREDIT_LMT<5000000.00 THEN '12DA1'-- 
               WHEN T7.CONTRACT_GUAR_TP='01' AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12DA2'-- 
               WHEN T7.CONTRACT_GUAR_TP='01' AND T5.CREDIT_LMT>=10000000.00 THEN '12DA3'--
               WHEN T7.CONTRACT_GUAR_TP='02' AND T5.CREDIT_LMT<5000000.00 THEN '12DB1'-- 
               WHEN T7.CONTRACT_GUAR_TP='02' AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12DB2'-- 
               WHEN T7.CONTRACT_GUAR_TP='02' AND T5.CREDIT_LMT>=10000000.00 THEN '12DB3'--
               WHEN T7.CONTRACT_GUAR_TP='03' AND T5.CREDIT_LMT<5000000.00 THEN '12DC1'-- 
               WHEN T7.CONTRACT_GUAR_TP='03' AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12DC2'-- 
               WHEN T7.CONTRACT_GUAR_TP='03' AND T5.CREDIT_LMT>=10000000.00 THEN '12DC3'--
               WHEN T7.CONTRACT_GUAR_TP='04' AND T5.CREDIT_LMT<5000000.00 THEN '12DD1'-- 
               WHEN T7.CONTRACT_GUAR_TP='04' AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12DD2'-- 
               WHEN T7.CONTRACT_GUAR_TP='04' AND T5.CREDIT_LMT>=10000000.00 THEN '12DD3'--
               WHEN T7.CONTRACT_GUAR_TP='05' AND T5.CREDIT_LMT<5000000.00 THEN '12DE1'-- 
               WHEN T7.CONTRACT_GUAR_TP='05' AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12DE2'-- 
               WHEN T7.CONTRACT_GUAR_TP='05' AND T5.CREDIT_LMT>=10000000.00 THEN '12DE3'--         
               END                                                       AS INDEX_NO
       ,SUM(CASE WHEN T1.CCY<>'CNY' THEN T1.BAL*T3.RATE ELSE T1.BAL END) AS INDEX_VALUE
                
FROM B_GEMS_LOAN_INFO T1

LEFT JOIN B_PBLC_INST_INFO T2--机构信息表
ON T1.ACTOPE_INST_ID=T2.INST_ID--贷款在网点办理
AND T2.ACCTG_DT='20241031'

LEFT JOIN (SELECT PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME
           FROM B_PBLC_INST_INFO--机构信息表
           WHERE ACCTG_DT='20241031'
           GROUP BY PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME) T2_1
ON T1.ACTOPE_INST_ID=T2_1.DOMN_INST_ID--贷款在辖行办理           

LEFT JOIN CCY_RATE T3
ON T1.CCY=T3.CCY_OLD
AND T3.CCY_NEW='CNY'
AND BGN_DT<=DATE'2024-10-31'
AND END_DT> DATE'2024-10-31'

LEFT JOIN B_ECIF_CUST_LMT T5--客户授信额度表
ON T1.CUST_ID=T5.CUST_ID
AND T5.ACCTG_DT='20241031'

LEFT JOIN B_GEMS_LOAN_CONTRACT_INFO T7 --贷款合同表
ON T1.UNVS_AGM_NO=T7.UNVS_AGM_NO
AND T1.AGM_MODIF=T7.AGM_MODIF
AND T7.ACCTG_DT='20241031'

WHERE T1.ACCTG_DT='20241031'--月底最后一天 
AND T1.BAL<>'0'--余额未结清
AND (T1.ACCTG_SBJEC_ID LIKE '121%' OR T1.ACCTG_SBJEC_ID LIKE '123%')--科目号121和123开头

GROUP BY COALESCE(T2.INST_ID,T2_1.DOMN_INST_ID)--
         ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)-- 
         ,CASE WHEN T7.CONTRACT_GUAR_TP='01' AND T5.CREDIT_LMT<5000000.00 THEN '12DA1'-- 
               WHEN T7.CONTRACT_GUAR_TP='01' AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12DA2'-- 
               WHEN T7.CONTRACT_GUAR_TP='01' AND T5.CREDIT_LMT>=10000000.00 THEN '12DA3'--
               WHEN T7.CONTRACT_GUAR_TP='02' AND T5.CREDIT_LMT<5000000.00 THEN '12DB1'-- 
               WHEN T7.CONTRACT_GUAR_TP='02' AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12DB2'-- 
               WHEN T7.CONTRACT_GUAR_TP='02' AND T5.CREDIT_LMT>=10000000.00 THEN '12DB3'--
               WHEN T7.CONTRACT_GUAR_TP='03' AND T5.CREDIT_LMT<5000000.00 THEN '12DC1'-- 
               WHEN T7.CONTRACT_GUAR_TP='03' AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12DC2'-- 
               WHEN T7.CONTRACT_GUAR_TP='03' AND T5.CREDIT_LMT>=10000000.00 THEN '12DC3'--
               WHEN T7.CONTRACT_GUAR_TP='04' AND T5.CREDIT_LMT<5000000.00 THEN '12DD1'-- 
               WHEN T7.CONTRACT_GUAR_TP='04' AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12DD2'-- 
               WHEN T7.CONTRACT_GUAR_TP='04' AND T5.CREDIT_LMT>=10000000.00 THEN '12DD3'--
               WHEN T7.CONTRACT_GUAR_TP='05' AND T5.CREDIT_LMT<5000000.00 THEN '12DE1'-- 
               WHEN T7.CONTRACT_GUAR_TP='05' AND (T5.CREDIT_LMT>=5000000.00 AND T5.CREDIT_LMT<10000000.00) THEN '12DE2'-- 
               WHEN T7.CONTRACT_GUAR_TP='05' AND T5.CREDIT_LMT>=10000000.00 THEN '12DE3'--         
               END--可能存在null
) WHERE INDEX_NO IS NOT NULL
),
--------------------------------------------------------------------------------------------
INST_GDE_3TH_TMP AS(
SELECT DATE'2024-10-31'                                                     AS ACCTG_DT
       ,COALESCE(T2.DOMN_INST_ID,T2_1.DOMN_INST_ID)                         AS INST_ID
       ,COALESCE(T2.DOMN_INST_NME,T2_1.DOMN_INST_NME)                       AS INST_NME
       ,'3'                                                                 AS INST_GDE
       ,T8.INDEX_NO                                                         AS INDEX_NO
       ,SUM(T8.INDEX_VALUE)                                                 AS INDEX_VALUE

FROM INST_GDE_4TH_TMP T8--四级机构统计临时表

LEFT JOIN B_PBLC_INST_INFO T2--机构信息表
ON T8.INST_ID=T2.INST_ID
AND T2.ACCTG_DT='20241031'

LEFT JOIN (SELECT PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME
           FROM B_PBLC_INST_INFO--机构信息表
           WHERE ACCTG_DT='20241031'
           GROUP BY PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME) T2_1
ON T8.INST_ID=T2_1.DOMN_INST_ID--贷款在辖行办理

GROUP BY COALESCE(T2.DOMN_INST_ID,T2_1.DOMN_INST_ID)
         ,COALESCE(T2.DOMN_INST_NME,T2_1.DOMN_INST_NME)
         ,T8.INDEX_NO         
),
--------------------------------------------------------------------------------------------
INST_GDE_2TH_TMP AS(
SELECT DATE'2024-10-31'                                                                   AS ACCTG_DT
       ,COALESCE(T2.PROV_INST_ID,T2.DOMN_INST_ID,T2_1.PROV_INST_ID,T2_1.DOMN_INST_ID)     AS INST_ID
       ,COALESCE(T2.PROV_INST_NME,T2.DOMN_INST_NME,T2_1.PROV_INST_NME,T2.DOMN_INST_NME)   AS INST_NME
       ,'2'                                                                               AS INST_GDE
       ,T8.INDEX_NO                                                                       AS INDEX_NO
       ,SUM(T8.INDEX_VALUE)                                                               AS INDEX_VALUE
       
FROM INST_GDE_4TH_TMP T8--四级机构统计临时表

LEFT JOIN B_PBLC_INST_INFO T2--机构信息表
ON T8.INST_ID=T2.INST_ID
AND T2.ACCTG_DT='20241031'

LEFT JOIN (SELECT PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME
           FROM B_PBLC_INST_INFO--机构信息表
           WHERE ACCTG_DT='20241031'
           GROUP BY PROV_INST_ID,PROV_INST_NME,DOMN_INST_ID,DOMN_INST_NME) T2_1
ON T8.INST_ID=T2_1.DOMN_INST_ID--贷款在辖行办理

GROUP BY COALESCE(T2.PROV_INST_ID,T2.DOMN_INST_ID,T2_1.PROV_INST_ID,T2_1.DOMN_INST_ID)
         ,COALESCE(T2.PROV_INST_NME,T2.DOMN_INST_NME,T2_1.PROV_INST_NME,T2.DOMN_INST_NME)
         ,T8.INDEX_NO
),
--------------------------------------------------------------------------------------------
INST_GDE_1TH_TMP AS(
SELECT DATE'2024-10-31'                                                                   AS ACCTG_DT
       ,'境内汇总'                                                                        AS INST_ID
       ,'境内汇总'                                                                        AS INST_NME
       ,'1'                                                                               AS INST_GDE
       ,T8.INDEX_NO                                                                       AS INDEX_NO
       ,SUM(T8.INDEX_VALUE)                                                               AS INDEX_VALUE   
FROM INST_GDE_4TH_TMP T8--四级机构统计临时表
GROUP BY T8.INDEX_NO
)
--------------------------------------------------------------------------------------------
/*DELETE FROM CTD_LOAD_INDEX WHERE ACCTG_DT=DATE'2024-10-31';
INSERT INTO CTD_LOAD_INDEX(
                           ACCTG_DT
                           ,INST_ID
                           ,INST_NME
                           ,INST_GDE
                           ,INDEX_NO
                           ,INDEX_VALUE
)*/
SELECT * FROM INST_GDE_1TH_TMP 
UNION ALL
SELECT * FROM INST_GDE_2TH_TMP
UNION ALL
SELECT * FROM INST_GDE_3TH_TMP
UNION ALL
SELECT TMP_4.ACCTG_DT
       ,TMP_4.INST_ID
       ,TMP_4.INST_NME
       ,TMP_4.INST_GDE
       ,TMP_4.INDEX_NO
       ,TMP_4.INDEX_VALUE
FROM INST_GDE_4TH_TMP TMP_4
LEFT JOIN (SELECT DOMN_INST_ID
          FROM B_PBLC_INST_INFO
          WHERE ACCTG_DT='20241031'
          GROUP BY DOMN_INST_ID) T9
ON TMP_4.INST_ID=T9.DOMN_INST_ID
WHERE T9.DOMN_INST_ID IS NULL
