--删除当月数据支持重跑
DELETE FROM QYDWDKZBB WHERE ACCTG_DT = TO_DATE('2024-10-31','YYYY-MM-DD');

----------------------插入网点数据--------------------------
INSERT INTO QYDWDKZBB(
     ACCTG_DT
    ,INST_ID 
    ,INST_NME
    ,INST_LEV
    ,IND_ID  
    ,IND_VAL 
)
--插入贸易融资与非贸易融资数据
SELECT TO_DATE('2024-10-31','YYYY-MM-DD')                                 AS ACCTG_DT
      ,T1.ACTOPE_INST_ID                                                  AS INST_ID
	  ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)                           AS INST_NME
	  ,'4'                                                                AS INST_LEV
	  ,CASE WHEN T1.ACCTG_SBJEC_ID LIKE '121%' THEN '12AA'                
            WHEN T1.ACCTG_SBJEC_ID LIKE '123%' THEN '22AA' END            AS IND_ID
	  ,SUM(CASE WHEN T1.CCY <> 'CNY' THEN T1.BAL*T8.RATE ELSE T1.BAL END) AS IND_VAL
FROM B_GEMS_LOAN_INFO                  T1
 
LEFT JOIN B_PBLC_INST_INFO             T2
     ON T1.ACTOPE_INST_ID = T2.INST_ID
 	 AND T2.ACCTG_DT = '20241031'
 
LEFT JOIN (SELECT DOMN_INST_ID, DOMN_INST_NME
           FROM B_PBLC_INST_INFO
           WHERE ACCTG_DT = '20241031'
           GROUP BY DOMN_INST_ID, DOMN_INST_NME)	T2_1
     ON T1.ACTOPE_INST_ID = T2_1.DOMN_INST_ID

LEFT JOIN CCY_RATE                     T8
     ON T1.CCY = T8.CCY_OLD
	 AND T8.CCY_NEW = 'CNY'
	 AND T8.BGN_DT <= DATE'2024-10-31'
	 AND T8.END_DT >  DATE'2024-10-31'
	 AND T8.COUNT_FLG = '00' 
	 
WHERE T1.ACCTG_DT = '20241031'
AND T1.BAL <> 0
AND SUBSTR(T1.ACCTG_SBJEC_ID,1,3) IN ('121','123')
GROUP BY T1.ACTOPE_INST_ID, COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME), 
         CASE WHEN T1.ACCTG_SBJEC_ID LIKE '121%' THEN '12AA' WHEN T1.ACCTG_SBJEC_ID LIKE '123%' THEN '22AA' END
 
UNION ALL
--插入不同企业规模的数据
SELECT TO_DATE('2024-10-31','YYYY-MM-DD')                                 AS ACCTG_DT
      ,T1.ACTOPE_INST_ID                                                  AS INST_ID
	  ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)                           AS INST_NME
	  ,'4'                                                                AS INST_LEV
	  ,CASE WHEN T3.ENTP_SCAL_CD IN ('01','02') THEN '12AB'               
            WHEN T3.ENTP_SCAL_CD = '03' THEN '12AC'                       
			WHEN T3.ENTP_SCAL_CD = '04' THEN '12AD' END                   AS IND_ID
	  ,SUM(CASE WHEN T1.CCY <> 'CNY' THEN T1.BAL*T8.RATE ELSE T1.BAL END) AS IND_VAL
FROM B_GEMS_LOAN_INFO                  T1
 
LEFT JOIN B_PBLC_INST_INFO             T2
     ON T1.ACTOPE_INST_ID = T2.INST_ID
 	 AND T2.ACCTG_DT = '20241031'

LEFT JOIN (SELECT DOMN_INST_ID, DOMN_INST_NME
           FROM B_PBLC_INST_INFO
           WHERE ACCTG_DT = '20241031'
           GROUP BY DOMN_INST_ID, DOMN_INST_NME)	T2_1
     ON T1.ACTOPE_INST_ID = T2_1.DOMN_INST_ID

LEFT JOIN CCY_RATE                     T8
     ON T1.CCY = T8.CCY_OLD
	 AND T8.CCY_NEW = 'CNY'
	 AND T8.BGN_DT <= DATE'2024-10-31'
	 AND T8.END_DT >  DATE'2024-10-31'
	 AND T8.COUNT_FLG = '00'

LEFT JOIN B_ECIF_CUST_INFO_C	       T3
	 ON T1.CUST_ID = T3.CUST_ID
	 AND T3.ACCTG_DT = '20241031'
	 
WHERE T1.ACCTG_DT = '20241031'
AND T1.BAL <> 0
AND SUBSTR(T1.ACCTG_SBJEC_ID,1,3) IN ('121','123')
GROUP BY T1.ACTOPE_INST_ID, COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME),
         CASE WHEN T3.ENTP_SCAL_CD IN ('01','02') THEN '12AB'
              WHEN T3.ENTP_SCAL_CD = '03' THEN '12AC'
			  WHEN T3.ENTP_SCAL_CD = '04' THEN '12AD' END

UNION ALL
--插入不同企业规模不同额度的数据
SELECT TO_DATE('2024-10-31','YYYY-MM-DD')                                 AS ACCTG_DT
      ,T1.ACTOPE_INST_ID                                                  AS INST_ID
	  ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)                           AS INST_NME
	  ,'4'                                                                AS INST_LEV
	  ,CASE WHEN T3.ENTP_SCAL_CD IN ('01','02') AND 5000000  >  T4.CREDIT_LMT            THEN '12AB1'
            WHEN T3.ENTP_SCAL_CD IN ('01','02') AND 10000000 >  T4.CREDIT_LMT            THEN '12AB2'
			WHEN T3.ENTP_SCAL_CD IN ('01','02') AND 10000000 <= T4.CREDIT_LMT            THEN '12AB3' 
			WHEN T3.ENTP_SCAL_CD = '03'         AND 5000000  >  T4.CREDIT_LMT            THEN '12AC1'
			WHEN T3.ENTP_SCAL_CD = '03'         AND 10000000 >  T4.CREDIT_LMT            THEN '12AC2'
			WHEN T3.ENTP_SCAL_CD = '03'         AND 10000000 <= T4.CREDIT_LMT            THEN '12AC3'
			WHEN T3.ENTP_SCAL_CD = '04'         AND 5000000  >  T4.CREDIT_LMT            THEN '12AD1'
			WHEN T3.ENTP_SCAL_CD = '04'         AND 10000000 >  T4.CREDIT_LMT            THEN '12AD2'
			WHEN T3.ENTP_SCAL_CD = '04'         AND 10000000 <= T4.CREDIT_LMT            THEN '12AD3'
	   END                                                                AS IND_ID
	  ,SUM(CASE WHEN T1.CCY <> 'CNY' THEN T1.BAL*T8.RATE ELSE T1.BAL END) AS IND_VAL
FROM B_GEMS_LOAN_INFO                  T1
 
LEFT JOIN B_PBLC_INST_INFO             T2
     ON T1.ACTOPE_INST_ID = T2.INST_ID
 	 AND T2.ACCTG_DT = '20241031'

LEFT JOIN (SELECT DOMN_INST_ID, DOMN_INST_NME
           FROM B_PBLC_INST_INFO
           WHERE ACCTG_DT = '20241031'
           GROUP BY DOMN_INST_ID, DOMN_INST_NME)	T2_1
     ON T1.ACTOPE_INST_ID = T2_1.DOMN_INST_ID

LEFT JOIN CCY_RATE                     T8
     ON T1.CCY = T8.CCY_OLD
	 AND T8.CCY_NEW = 'CNY'
	 AND T8.BGN_DT <= DATE'2024-10-31'
	 AND T8.END_DT >  DATE'2024-10-31'
	 AND T8.COUNT_FLG = '00'

LEFT JOIN B_ECIF_CUST_INFO_C	       T3
	 ON T1.CUST_ID = T3.CUST_ID
	 AND T3.ACCTG_DT = '20241031'

LEFT JOIN B_ECIF_CUST_LMT              T4
     ON T1.CUST_ID = T4.CUST_ID
     AND T4.ACCTG_DT = '20241031'
	 
WHERE T1.ACCTG_DT = '20241031'
AND T1.BAL <> 0
AND SUBSTR(T1.ACCTG_SBJEC_ID,1,3) IN ('121','123')
GROUP BY T1.ACTOPE_INST_ID, COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME),
       CASE WHEN T3.ENTP_SCAL_CD IN ('01','02') AND 5000000  >  T4.CREDIT_LMT            THEN '12AB1'
            WHEN T3.ENTP_SCAL_CD IN ('01','02') AND 10000000 >  T4.CREDIT_LMT            THEN '12AB2'
			WHEN T3.ENTP_SCAL_CD IN ('01','02') AND 10000000 <= T4.CREDIT_LMT            THEN '12AB3' 
			WHEN T3.ENTP_SCAL_CD = '03'         AND 5000000  >  T4.CREDIT_LMT            THEN '12AC1'
			WHEN T3.ENTP_SCAL_CD = '03'         AND 10000000 >  T4.CREDIT_LMT            THEN '12AC2'
			WHEN T3.ENTP_SCAL_CD = '03'         AND 10000000 <= T4.CREDIT_LMT            THEN '12AC3'
			WHEN T3.ENTP_SCAL_CD = '04'         AND 5000000  >  T4.CREDIT_LMT            THEN '12AD1'
			WHEN T3.ENTP_SCAL_CD = '04'         AND 10000000 >  T4.CREDIT_LMT            THEN '12AD2'
			WHEN T3.ENTP_SCAL_CD = '04'         AND 10000000 <= T4.CREDIT_LMT            THEN '12AD3'
	   END

UNION ALL	   
--插入不同五级分类的数据
SELECT TO_DATE('2024-10-31','YYYY-MM-DD')                                 AS ACCTG_DT
      ,T1.ACTOPE_INST_ID                                                  AS INST_ID
	  ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)                           AS INST_NME
	  ,'4'                                                                AS INST_LEV
	  ,CASE WHEN T3.FINAL_FIVE_CLASS = '1' THEN '12BA'
            WHEN T3.FINAL_FIVE_CLASS = '2' THEN '12BB'
			WHEN T3.FINAL_FIVE_CLASS = '3' THEN '12BC'
			WHEN T3.FINAL_FIVE_CLASS = '4' THEN '12BD'
			WHEN T3.FINAL_FIVE_CLASS = '5' THEN '12BE'
	   END                                                                AS IND_ID
	  ,SUM(CASE WHEN T1.CCY <> 'CNY' THEN T1.BAL*T8.RATE ELSE T1.BAL END) AS IND_VAL
FROM B_GEMS_LOAN_INFO                  T1
 
LEFT JOIN B_PBLC_INST_INFO             T2
     ON T1.ACTOPE_INST_ID = T2.INST_ID
 	 AND T2.ACCTG_DT = '20241031'

LEFT JOIN (SELECT DOMN_INST_ID, DOMN_INST_NME
           FROM B_PBLC_INST_INFO
           WHERE ACCTG_DT = '20241031'
           GROUP BY DOMN_INST_ID, DOMN_INST_NME)	T2_1
     ON T1.ACTOPE_INST_ID = T2_1.DOMN_INST_ID

LEFT JOIN CCY_RATE                     T8
     ON T1.CCY = T8.CCY_OLD
	 AND T8.CCY_NEW = 'CNY'
	 AND T8.BGN_DT <= DATE'2024-10-31'
	 AND T8.END_DT >  DATE'2024-10-31'
	 AND T8.COUNT_FLG = '00'

LEFT JOIN B_RISK_LOAN_FIVE_CLASS	   T3
	 ON T1.UNVS_AGM_NO = T3.UNVS_AGM_NO
	 AND T1.AGM_MODIF = T3.AGM_MODIF
	 AND T3.ACCTG_DT = '20241031'
	 
WHERE T1.ACCTG_DT = '20241031'
AND T1.BAL <> 0
AND SUBSTR(T1.ACCTG_SBJEC_ID,1,3) IN ('121','123')
GROUP BY T1.ACTOPE_INST_ID, COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME),
       CASE WHEN T3.FINAL_FIVE_CLASS = '1' THEN '12BA'
            WHEN T3.FINAL_FIVE_CLASS = '2' THEN '12BB'
			WHEN T3.FINAL_FIVE_CLASS = '3' THEN '12BC'
			WHEN T3.FINAL_FIVE_CLASS = '4' THEN '12BD'
			WHEN T3.FINAL_FIVE_CLASS = '5' THEN '12BE'
	   END
	   
UNION ALL	   
--插入不良贷款数据
SELECT TO_DATE('2024-10-31','YYYY-MM-DD')                                 AS ACCTG_DT
      ,T1.ACTOPE_INST_ID                                                  AS INST_ID
	  ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)                           AS INST_NME
	  ,'4'                                                                AS INST_LEV
	  ,'12BF'                                                             AS IND_ID
	  ,SUM(CASE WHEN T1.CCY <> 'CNY' THEN T1.BAL*T8.RATE ELSE T1.BAL END) AS IND_VAL
FROM B_GEMS_LOAN_INFO                  T1
 
LEFT JOIN B_PBLC_INST_INFO             T2
     ON T1.ACTOPE_INST_ID = T2.INST_ID
 	 AND T2.ACCTG_DT = '20241031'

LEFT JOIN (SELECT DOMN_INST_ID, DOMN_INST_NME
           FROM B_PBLC_INST_INFO
           WHERE ACCTG_DT = '20241031'
           GROUP BY DOMN_INST_ID, DOMN_INST_NME)	T2_1
     ON T1.ACTOPE_INST_ID = T2_1.DOMN_INST_ID

LEFT JOIN CCY_RATE                     T8
     ON T1.CCY = T8.CCY_OLD
	 AND T8.CCY_NEW = 'CNY'
	 AND T8.BGN_DT <= DATE'2024-10-31'
	 AND T8.END_DT >  DATE'2024-10-31'
	 AND T8.COUNT_FLG = '00'

LEFT JOIN B_RISK_LOAN_FIVE_CLASS	   T3
	 ON T1.UNVS_AGM_NO = T3.UNVS_AGM_NO
	 AND T1.AGM_MODIF = T3.AGM_MODIF
	 AND T3.ACCTG_DT = '20241031'
	 
WHERE T1.ACCTG_DT = '20241031'
AND T1.BAL <> 0
AND T3.FINAL_FIVE_CLASS IN ('3','4','5')
AND SUBSTR(T1.ACCTG_SBJEC_ID,1,3) IN ('121','123')
GROUP BY T1.ACTOPE_INST_ID, COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)

UNION ALL	   
--插入不同五级分类不同授信额度的数据
SELECT TO_DATE('2024-10-31','YYYY-MM-DD')                                 AS ACCTG_DT
      ,T1.ACTOPE_INST_ID                                                  AS INST_ID
	  ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)                           AS INST_NME
	  ,'4'                                                                AS INST_LEV
	  ,CASE WHEN T3.FINAL_FIVE_CLASS = '1' AND 5000000  >  T4.CREDIT_LMT THEN '12BA1'
            WHEN T3.FINAL_FIVE_CLASS = '1' AND 10000000 >  T4.CREDIT_LMT THEN '12BA2'
			WHEN T3.FINAL_FIVE_CLASS = '1' AND 10000000 <= T4.CREDIT_LMT THEN '12BA3'
			WHEN T3.FINAL_FIVE_CLASS = '2' AND 5000000  >  T4.CREDIT_LMT THEN '12BB1'
			WHEN T3.FINAL_FIVE_CLASS = '2' AND 10000000 >  T4.CREDIT_LMT THEN '12BB2'
			WHEN T3.FINAL_FIVE_CLASS = '2' AND 10000000 <= T4.CREDIT_LMT THEN '12BB3'
			WHEN T3.FINAL_FIVE_CLASS = '3' AND 5000000  >  T4.CREDIT_LMT THEN '12BC1'
			WHEN T3.FINAL_FIVE_CLASS = '3' AND 10000000 >  T4.CREDIT_LMT THEN '12BC2'
			WHEN T3.FINAL_FIVE_CLASS = '3' AND 10000000 <= T4.CREDIT_LMT THEN '12BC3'
			WHEN T3.FINAL_FIVE_CLASS = '4' AND 5000000  >  T4.CREDIT_LMT THEN '12BD1'
			WHEN T3.FINAL_FIVE_CLASS = '4' AND 10000000 >  T4.CREDIT_LMT THEN '12BD2'
			WHEN T3.FINAL_FIVE_CLASS = '4' AND 10000000 <= T4.CREDIT_LMT THEN '12BD3'
			WHEN T3.FINAL_FIVE_CLASS = '5' AND 5000000  >  T4.CREDIT_LMT THEN '12BE1'
			WHEN T3.FINAL_FIVE_CLASS = '5' AND 10000000 >  T4.CREDIT_LMT THEN '12BE2'
			WHEN T3.FINAL_FIVE_CLASS = '5' AND 10000000 <= T4.CREDIT_LMT THEN '12BE3'
	   END                                                                AS IND_ID
	  ,SUM(CASE WHEN T1.CCY <> 'CNY' THEN T1.BAL*T8.RATE ELSE T1.BAL END) AS IND_VAL
FROM B_GEMS_LOAN_INFO                  T1
 
LEFT JOIN B_PBLC_INST_INFO             T2
     ON T1.ACTOPE_INST_ID = T2.INST_ID
 	 AND T2.ACCTG_DT = '20241031'

LEFT JOIN (SELECT DOMN_INST_ID, DOMN_INST_NME
           FROM B_PBLC_INST_INFO
           WHERE ACCTG_DT = '20241031'
           GROUP BY DOMN_INST_ID, DOMN_INST_NME)	T2_1
     ON T1.ACTOPE_INST_ID = T2_1.DOMN_INST_ID

LEFT JOIN CCY_RATE                     T8
     ON T1.CCY = T8.CCY_OLD
	 AND T8.CCY_NEW = 'CNY'
	 AND T8.BGN_DT <= DATE'2024-10-31'
	 AND T8.END_DT >  DATE'2024-10-31'
	 AND T8.COUNT_FLG = '00'

LEFT JOIN B_RISK_LOAN_FIVE_CLASS	   T3
	 ON T1.UNVS_AGM_NO = T3.UNVS_AGM_NO
	 AND T1.AGM_MODIF = T3.AGM_MODIF
	 AND T3.ACCTG_DT = '20241031'

LEFT JOIN B_ECIF_CUST_LMT	           T4
	 ON T1.CUST_ID = T4.CUST_ID
	 AND T4.ACCTG_DT = '20241031'
	 
WHERE T1.ACCTG_DT = '20241031'
AND T1.BAL <> 0
AND SUBSTR(T1.ACCTG_SBJEC_ID,1,3) IN ('121','123')
GROUP BY T1.ACTOPE_INST_ID, COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME),
       CASE WHEN T3.FINAL_FIVE_CLASS = '1' AND 5000000  >  T4.CREDIT_LMT THEN '12BA1'
            WHEN T3.FINAL_FIVE_CLASS = '1' AND 10000000 >  T4.CREDIT_LMT THEN '12BA2'
			WHEN T3.FINAL_FIVE_CLASS = '1' AND 10000000 <= T4.CREDIT_LMT THEN '12BA3'
			WHEN T3.FINAL_FIVE_CLASS = '2' AND 5000000  >  T4.CREDIT_LMT THEN '12BB1'
			WHEN T3.FINAL_FIVE_CLASS = '2' AND 10000000 >  T4.CREDIT_LMT THEN '12BB2'
			WHEN T3.FINAL_FIVE_CLASS = '2' AND 10000000 <= T4.CREDIT_LMT THEN '12BB3'
			WHEN T3.FINAL_FIVE_CLASS = '3' AND 5000000  >  T4.CREDIT_LMT THEN '12BC1'
			WHEN T3.FINAL_FIVE_CLASS = '3' AND 10000000 >  T4.CREDIT_LMT THEN '12BC2'
			WHEN T3.FINAL_FIVE_CLASS = '3' AND 10000000 <= T4.CREDIT_LMT THEN '12BC3'
			WHEN T3.FINAL_FIVE_CLASS = '4' AND 5000000  >  T4.CREDIT_LMT THEN '12BD1'
			WHEN T3.FINAL_FIVE_CLASS = '4' AND 10000000 >  T4.CREDIT_LMT THEN '12BD2'
			WHEN T3.FINAL_FIVE_CLASS = '4' AND 10000000 <= T4.CREDIT_LMT THEN '12BD3'
			WHEN T3.FINAL_FIVE_CLASS = '5' AND 5000000  >  T4.CREDIT_LMT THEN '12BE1'
			WHEN T3.FINAL_FIVE_CLASS = '5' AND 10000000 >  T4.CREDIT_LMT THEN '12BE2'
			WHEN T3.FINAL_FIVE_CLASS = '5' AND 10000000 <= T4.CREDIT_LMT THEN '12BE3'
	   END
	   
UNION ALL	   
--插入不同控股方式的的数据
SELECT TO_DATE('2024-10-31','YYYY-MM-DD')                                 AS ACCTG_DT
      ,T1.ACTOPE_INST_ID                                                  AS INST_ID
	  ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)                           AS INST_NME
	  ,'4'                                                                AS INST_LEV
	  ,CASE WHEN T4.HOLD_SHARE = 'COL' THEN '12CA'
            WHEN T4.HOLD_SHARE = 'PER' THEN '12CB'
			WHEN T4.HOLD_SHARE = 'HAT' THEN '12CC'
			WHEN T4.HOLD_SHARE = 'FOR' THEN '12CD'
			WHEN T4.HOLD_SHARE = 'CTY' THEN '12CE'
	   END                                                                AS IND_ID
	  ,SUM(CASE WHEN T1.CCY <> 'CNY' THEN T1.BAL*T8.RATE ELSE T1.BAL END) AS IND_VAL
FROM B_GEMS_LOAN_INFO                  T1
 
LEFT JOIN B_PBLC_INST_INFO             T2
     ON T1.ACTOPE_INST_ID = T2.INST_ID
 	 AND T2.ACCTG_DT = '20241031'

LEFT JOIN (SELECT DOMN_INST_ID, DOMN_INST_NME
           FROM B_PBLC_INST_INFO
           WHERE ACCTG_DT = '20241031'
           GROUP BY DOMN_INST_ID, DOMN_INST_NME)	T2_1
     ON T1.ACTOPE_INST_ID = T2_1.DOMN_INST_ID

LEFT JOIN CCY_RATE                     T8
     ON T1.CCY = T8.CCY_OLD
	 AND T8.CCY_NEW = 'CNY'
	 AND T8.BGN_DT <= DATE'2024-10-31'
	 AND T8.END_DT >  DATE'2024-10-31'
	 AND T8.COUNT_FLG = '00'

LEFT JOIN B_RISK_LOAN_FIVE_CLASS	   T3
	 ON T1.UNVS_AGM_NO = T3.UNVS_AGM_NO
	 AND T1.AGM_MODIF = T3.AGM_MODIF
	 AND T3.ACCTG_DT = '20241031'

LEFT JOIN B_ECIF_CUST_INFO_C	       T4
	 ON T1.CUST_ID = T4.CUST_ID
	 AND T4.ACCTG_DT = '20241031'
	 
WHERE T1.ACCTG_DT = '20241031'
AND T1.BAL <> 0
AND SUBSTR(T1.ACCTG_SBJEC_ID,1,3) IN ('121','123')
GROUP BY T1.ACTOPE_INST_ID, COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME),
       CASE WHEN T4.HOLD_SHARE = 'COL' THEN '12CA'
            WHEN T4.HOLD_SHARE = 'PER' THEN '12CB'
			WHEN T4.HOLD_SHARE = 'HAT' THEN '12CC'
			WHEN T4.HOLD_SHARE = 'FOR' THEN '12CD'
			WHEN T4.HOLD_SHARE = 'CTY' THEN '12CE'
	   END
	   
UNION ALL	   
--插入不同控股方式的的不良贷款数据
SELECT TO_DATE('2024-10-31','YYYY-MM-DD')                                 AS ACCTG_DT
      ,T1.ACTOPE_INST_ID                                                  AS INST_ID
	  ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)                           AS INST_NME
	  ,'4'                                                                AS INST_LEV
	  ,CASE WHEN T4.HOLD_SHARE = 'COL' THEN '12CA1'
            WHEN T4.HOLD_SHARE = 'PER' THEN '12CB1'
			WHEN T4.HOLD_SHARE = 'HAT' THEN '12CC1'
			WHEN T4.HOLD_SHARE = 'FOR' THEN '12CD1'
			WHEN T4.HOLD_SHARE = 'CTY' THEN '12CE1'
	   END                                                                AS IND_ID
	  ,SUM(CASE WHEN T1.CCY <> 'CNY' THEN T1.BAL*T8.RATE ELSE T1.BAL END) AS IND_VAL
FROM B_GEMS_LOAN_INFO                  T1
 
LEFT JOIN B_PBLC_INST_INFO             T2
     ON T1.ACTOPE_INST_ID = T2.INST_ID
 	 AND T2.ACCTG_DT = '20241031'

LEFT JOIN (SELECT DOMN_INST_ID, DOMN_INST_NME
           FROM B_PBLC_INST_INFO
           WHERE ACCTG_DT = '20241031'
           GROUP BY DOMN_INST_ID, DOMN_INST_NME)	T2_1
     ON T1.ACTOPE_INST_ID = T2_1.DOMN_INST_ID

LEFT JOIN CCY_RATE                     T8
     ON T1.CCY = T8.CCY_OLD
	 AND T8.CCY_NEW = 'CNY'
	 AND T8.BGN_DT <= DATE'2024-10-31'
	 AND T8.END_DT >  DATE'2024-10-31'
	 AND T8.COUNT_FLG = '00'

LEFT JOIN B_RISK_LOAN_FIVE_CLASS	   T3
	 ON T1.UNVS_AGM_NO = T3.UNVS_AGM_NO
	 AND T1.AGM_MODIF = T3.AGM_MODIF
	 AND T3.ACCTG_DT = '20241031'

LEFT JOIN B_ECIF_CUST_INFO_C	       T4
	 ON T1.CUST_ID = T4.CUST_ID
	 AND T4.ACCTG_DT = '20241031'
	 
WHERE T1.ACCTG_DT = '20241031'
AND T1.BAL <> 0
AND T3.FINAL_FIVE_CLASS IN ('3','4','5')
AND SUBSTR(T1.ACCTG_SBJEC_ID,1,3) IN ('121','123')
GROUP BY T1.ACTOPE_INST_ID, COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME),
       CASE WHEN T4.HOLD_SHARE = 'COL' THEN '12CA1'
            WHEN T4.HOLD_SHARE = 'PER' THEN '12CB1'
			WHEN T4.HOLD_SHARE = 'HAT' THEN '12CC1'
			WHEN T4.HOLD_SHARE = 'FOR' THEN '12CD1'
			WHEN T4.HOLD_SHARE = 'CTY' THEN '12CE1'
	   END
	   
UNION ALL	   
--插入不同担保方式的数据
SELECT TO_DATE('2024-10-31','YYYY-MM-DD')                                 AS ACCTG_DT
      ,T1.ACTOPE_INST_ID                                                  AS INST_ID
	  ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)                           AS INST_NME
	  ,'4'                                                                AS INST_LEV
	  ,CASE WHEN T3.CONTRACT_GUAR_TP = '01' THEN '12DA'
            WHEN T3.CONTRACT_GUAR_TP = '02' THEN '12DB'
			WHEN T3.CONTRACT_GUAR_TP = '03' THEN '12DC'
			WHEN T3.CONTRACT_GUAR_TP = '04' THEN '12DD'
			WHEN T3.CONTRACT_GUAR_TP = '05' THEN '12DE'
	   END                                                                AS IND_ID
	  ,SUM(CASE WHEN T1.CCY <> 'CNY' THEN T1.BAL*T8.RATE ELSE T1.BAL END) AS IND_VAL
FROM B_GEMS_LOAN_INFO                  T1
 
LEFT JOIN B_PBLC_INST_INFO             T2
     ON T1.ACTOPE_INST_ID = T2.INST_ID
 	 AND T2.ACCTG_DT = '20241031'

LEFT JOIN (SELECT DOMN_INST_ID, DOMN_INST_NME
           FROM B_PBLC_INST_INFO
           WHERE ACCTG_DT = '20241031'
           GROUP BY DOMN_INST_ID, DOMN_INST_NME)	T2_1
     ON T1.ACTOPE_INST_ID = T2_1.DOMN_INST_ID

LEFT JOIN CCY_RATE                     T8
     ON T1.CCY = T8.CCY_OLD
	 AND T8.CCY_NEW = 'CNY'
	 AND T8.BGN_DT <= DATE'2024-10-31'
	 AND T8.END_DT >  DATE'2024-10-31'
	 AND T8.COUNT_FLG = '00'

LEFT JOIN B_GEMS_LOAN_CONTRACT_INFO	   T3
	 ON T1.UNVS_AGM_NO = T3.UNVS_AGM_NO
	 AND T1.AGM_MODIF = T3.AGM_MODIF
	 AND T3.ACCTG_DT = '20241031'
	 
WHERE T1.ACCTG_DT = '20241031'
AND T1.BAL <> 0
AND SUBSTR(T1.ACCTG_SBJEC_ID,1,3) IN ('121','123')
GROUP BY T1.ACTOPE_INST_ID, COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME),
       CASE WHEN T3.CONTRACT_GUAR_TP = '01' THEN '12DA'
            WHEN T3.CONTRACT_GUAR_TP = '02' THEN '12DB'
			WHEN T3.CONTRACT_GUAR_TP = '03' THEN '12DC'
			WHEN T3.CONTRACT_GUAR_TP = '04' THEN '12DD'
			WHEN T3.CONTRACT_GUAR_TP = '05' THEN '12DE'
	   END
	   
UNION ALL	   
--插入不同担保方式不同授信额度的数据
SELECT TO_DATE('2024-10-31','YYYY-MM-DD')                                 AS ACCTG_DT
      ,T1.ACTOPE_INST_ID                                                  AS INST_ID
	  ,COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME)                           AS INST_NME
	  ,'4'                                                                AS INST_LEV
	  ,CASE WHEN T3.CONTRACT_GUAR_TP = '01' AND 5000000  >  T4.CREDIT_LMT THEN '12DA1'
            WHEN T3.CONTRACT_GUAR_TP = '01' AND 10000000 >  T4.CREDIT_LMT THEN '12DA2'
			WHEN T3.CONTRACT_GUAR_TP = '01' AND 10000000 <= T4.CREDIT_LMT THEN '12DA3'
			WHEN T3.CONTRACT_GUAR_TP = '02' AND 5000000  >  T4.CREDIT_LMT THEN '12DB1'
			WHEN T3.CONTRACT_GUAR_TP = '02' AND 10000000 >  T4.CREDIT_LMT THEN '12DB2'
			WHEN T3.CONTRACT_GUAR_TP = '02' AND 10000000 <= T4.CREDIT_LMT THEN '12DB3'
			WHEN T3.CONTRACT_GUAR_TP = '03' AND 5000000  >  T4.CREDIT_LMT THEN '12DC1'
			WHEN T3.CONTRACT_GUAR_TP = '03' AND 10000000 >  T4.CREDIT_LMT THEN '12DC2'
			WHEN T3.CONTRACT_GUAR_TP = '03' AND 10000000 <= T4.CREDIT_LMT THEN '12DC3'
			WHEN T3.CONTRACT_GUAR_TP = '04' AND 5000000  >  T4.CREDIT_LMT THEN '12DD1'
			WHEN T3.CONTRACT_GUAR_TP = '04' AND 10000000 >  T4.CREDIT_LMT THEN '12DD2'
			WHEN T3.CONTRACT_GUAR_TP = '04' AND 10000000 <= T4.CREDIT_LMT THEN '12DD3'
			WHEN T3.CONTRACT_GUAR_TP = '05' AND 5000000  >  T4.CREDIT_LMT THEN '12DE1'
			WHEN T3.CONTRACT_GUAR_TP = '05' AND 10000000 >  T4.CREDIT_LMT THEN '12DE2'
			WHEN T3.CONTRACT_GUAR_TP = '05' AND 10000000 <= T4.CREDIT_LMT THEN '12DE3'
	   END                                                                AS IND_ID
	  ,SUM(CASE WHEN T1.CCY <> 'CNY' THEN T1.BAL*T8.RATE ELSE T1.BAL END) AS IND_VAL
FROM B_GEMS_LOAN_INFO                  T1
 
LEFT JOIN B_PBLC_INST_INFO             T2
     ON T1.ACTOPE_INST_ID = T2.INST_ID
 	 AND T2.ACCTG_DT = '20241031'

LEFT JOIN (SELECT DOMN_INST_ID, DOMN_INST_NME
           FROM B_PBLC_INST_INFO
           WHERE ACCTG_DT = '20241031'
           GROUP BY DOMN_INST_ID, DOMN_INST_NME)	T2_1
     ON T1.ACTOPE_INST_ID = T2_1.DOMN_INST_ID

LEFT JOIN CCY_RATE                     T8
     ON T1.CCY = T8.CCY_OLD
	 AND T8.CCY_NEW = 'CNY'
	 AND T8.BGN_DT <= DATE'2024-10-31'
	 AND T8.END_DT >  DATE'2024-10-31'
	 AND T8.COUNT_FLG = '00'

LEFT JOIN B_GEMS_LOAN_CONTRACT_INFO	   T3
	 ON T1.UNVS_AGM_NO = T3.UNVS_AGM_NO
	 AND T1.AGM_MODIF = T3.AGM_MODIF
	 AND T3.ACCTG_DT = '20241031'

LEFT JOIN B_ECIF_CUST_LMT   	       T4
	 ON T1.CUST_ID = T4.CUST_ID
	 AND T4.ACCTG_DT = '20241031'
	 
WHERE T1.ACCTG_DT = '20241031'
AND T1.BAL <> 0
AND SUBSTR(T1.ACCTG_SBJEC_ID,1,3) IN ('121','123')
GROUP BY T1.ACTOPE_INST_ID, COALESCE(T2.INST_NME,T2_1.DOMN_INST_NME),
       CASE WHEN T3.CONTRACT_GUAR_TP = '01' AND 5000000  >  T4.CREDIT_LMT THEN '12DA1'
            WHEN T3.CONTRACT_GUAR_TP = '01' AND 10000000 >  T4.CREDIT_LMT THEN '12DA2'
			WHEN T3.CONTRACT_GUAR_TP = '01' AND 10000000 <= T4.CREDIT_LMT THEN '12DA3'
			WHEN T3.CONTRACT_GUAR_TP = '02' AND 5000000  >  T4.CREDIT_LMT THEN '12DB1'
			WHEN T3.CONTRACT_GUAR_TP = '02' AND 10000000 >  T4.CREDIT_LMT THEN '12DB2'
			WHEN T3.CONTRACT_GUAR_TP = '02' AND 10000000 <= T4.CREDIT_LMT THEN '12DB3'
			WHEN T3.CONTRACT_GUAR_TP = '03' AND 5000000  >  T4.CREDIT_LMT THEN '12DC1'
			WHEN T3.CONTRACT_GUAR_TP = '03' AND 10000000 >  T4.CREDIT_LMT THEN '12DC2'
			WHEN T3.CONTRACT_GUAR_TP = '03' AND 10000000 <= T4.CREDIT_LMT THEN '12DC3'
			WHEN T3.CONTRACT_GUAR_TP = '04' AND 5000000  >  T4.CREDIT_LMT THEN '12DD1'
			WHEN T3.CONTRACT_GUAR_TP = '04' AND 10000000 >  T4.CREDIT_LMT THEN '12DD2'
			WHEN T3.CONTRACT_GUAR_TP = '04' AND 10000000 <= T4.CREDIT_LMT THEN '12DD3'
			WHEN T3.CONTRACT_GUAR_TP = '05' AND 5000000  >  T4.CREDIT_LMT THEN '12DE1'
			WHEN T3.CONTRACT_GUAR_TP = '05' AND 10000000 >  T4.CREDIT_LMT THEN '12DE2'
			WHEN T3.CONTRACT_GUAR_TP = '05' AND 10000000 <= T4.CREDIT_LMT THEN '12DE3'
	   END
;


----------------------汇总成辖行的数据--------------------------
INSERT INTO QYDWDKZBB(
     ACCTG_DT
    ,INST_ID 
    ,INST_NME
    ,INST_LEV
    ,IND_ID  
    ,IND_VAL 
)
SELECT TO_DATE('2024-10-31','YYYY-MM-DD')                                 AS ACCTG_DT
      ,COALESCE(T2.DOMN_INST_ID,T2_1.DOMN_INST_ID)                        AS INST_ID
	  ,COALESCE(T2.DOMN_INST_NME,T2_1.DOMN_INST_NME)                      AS INST_NME
	  ,'3'                                                                AS INST_LEV
	  ,T1.IND_ID                                                          AS IND_ID
	  ,SUM(T1.IND_VAL)                                                    AS IND_VAL
FROM QYDWDKZBB                         T1
 
LEFT JOIN B_PBLC_INST_INFO             T2
     ON T1.INST_ID = T2.INST_ID
 	 AND T2.ACCTG_DT = '20241031'

LEFT JOIN (SELECT DOMN_INST_ID, DOMN_INST_NME
           FROM B_PBLC_INST_INFO
           WHERE ACCTG_DT = '20241031'
           GROUP BY DOMN_INST_ID, DOMN_INST_NME)	T2_1
     ON T1.INST_ID = T2_1.DOMN_INST_ID
	 
WHERE T1.ACCTG_DT = TO_DATE('2024-10-31','YYYY-MM-DD')
AND T1.INST_LEV = '4'
GROUP BY COALESCE(T2.DOMN_INST_ID,T2_1.DOMN_INST_ID), COALESCE(T2.DOMN_INST_NME,T2_1.DOMN_INST_NME), T1.IND_ID;

----------------------汇总成省分行的数据------------------------
INSERT INTO QYDWDKZBB(
     ACCTG_DT
    ,INST_ID 
    ,INST_NME
    ,INST_LEV
    ,IND_ID  
    ,IND_VAL 
)
SELECT TO_DATE('2024-10-31','YYYY-MM-DD')                                 AS ACCTG_DT
      ,COALESCE(T2.PROV_INST_ID,T2.DOMN_INST_ID)                          AS INST_ID
	  ,COALESCE(T2.PROV_INST_NME,T2.DOMN_INST_NME)                        AS INST_NME
	  ,'2'                                                                AS INST_LEV
	  ,T1.IND_ID                                                          AS IND_ID
	  ,SUM(T1.IND_VAL)                                                    AS IND_VAL
FROM QYDWDKZBB                         T1

LEFT JOIN (SELECT DOMN_INST_ID, DOMN_INST_NME, PROV_INST_ID, PROV_INST_NME
           FROM B_PBLC_INST_INFO
           WHERE ACCTG_DT = '20241031'
           GROUP BY DOMN_INST_ID, PROV_INST_ID, PROV_INST_NME, DOMN_INST_NME)	T2
     ON T1.INST_ID = T2.DOMN_INST_ID
	 
WHERE T1.ACCTG_DT = TO_DATE('2024-10-31','YYYY-MM-DD')
AND T1.INST_LEV = '3'
GROUP BY COALESCE(T2.PROV_INST_ID,T2.DOMN_INST_ID), COALESCE(T2.PROV_INST_NME,T2.DOMN_INST_NME), T1.IND_ID;


----------------------境内汇总------------------------
INSERT INTO QYDWDKZBB(
     ACCTG_DT
    ,INST_ID 
    ,INST_NME
    ,INST_LEV
    ,IND_ID  
    ,IND_VAL 
)
SELECT TO_DATE('2024-10-31','YYYY-MM-DD')                                 AS ACCTG_DT
      ,'99999999999'                                                      AS INST_ID
	  ,'境内汇总'                                                         AS INST_NME
	  ,'1'                                                                AS INST_LEV
	  ,T1.IND_ID                                                          AS IND_ID
	  ,SUM(T1.IND_VAL)                                                    AS IND_VAL
FROM QYDWDKZBB                         T1
	 
WHERE T1.ACCTG_DT = TO_DATE('2024-10-31','YYYY-MM-DD')
AND T1.INST_LEV = '2'
GROUP BY T1.IND_ID;


--删除直接发生在辖行的数据
DELETE FROM QYDWDKZBB A
WHERE INST_LEV = '4'  
AND EXISTS  (SELECT 1 FROM (SELECT DISTINCT DOMN_INST_ID FROM B_PBLC_INST_INFO WHERE ACCTG_DT = '20241031') B
             WHERE A.INST_ID = B.DOMN_INST_ID);